version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes: # mount volumes here
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes: # mount volumes here
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
