version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes: # mount volumes here
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 8000:8000
